micronaut:
  application:
    name: flutter-widgets-explorer
  security:
    authentication: bearer
    endpoints:
        login:
          enabled: true
        logout:
          enabled: true
          get-allowed: true
        #oauth:
        #  enabled: false
    token:
      jwt:
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: "${JWT_GENERATOR_REFRESH_SECRET:eefe82f8-7ca6-11ea-bc55-0242ac130003}"
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:eefe82f8-7ca6-11ea-bc55-0242ac130003}"'
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://accounts.google.com'

---
jackson:
  bean-introspection-module: true
---
datasources:
    default:
        url: ${db_url:`jdbc:mysql://localhost:3306/qprofit`}
        username: ${db_user:qprofit}
        password: ${db_password:`!qaz2WSX`}
        driverClassName: ${db_driver:org.mariadb.jdbc.Driver}
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
