micronaut:
  application:
    name: flutter-widgets-explorer
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
---
jackson:
  bean-introspection-module: true
---
datasources:
    default:
        url: ${db_url:`jdbc:mysql://localhost:3306/test`}
        username: ${db_user:root}
        password: ${db_password:`!qaz@wsx`}
        driverClassName: ${db_driver:org.mariadb.jdbc.Driver}
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
