micronaut:
  application:
    name: flutter-widgets-explorer
   
datasources:
    default:
        url: ${db_url:`jdbc:mysql://localhost:3306/test`}
        username: ${db_user:root}
        password: ${db_password:`!qaz@wsx`}
        driverClassName: ${db_driver:com.mysql.cj.jdbc.Driver}
        dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
